Remove buggy `Memory(::ByteData)` constructor.
JuliaIO/TranscodingStreams.jl pull request #219
Opened 2024-05-30 17:47 UTC by nhz2

Fixes #214

https://github.com/JuliaIO/TranscodingStreams.jl/blob/8fdabeda88199cd4298d9cba597e006b1af7655a/src/TranscodingStreams.jl#L8

This may cause issues as `CodeUnits` may not be stored densely in memory.
Ref: https://github.com/JuliaLang/julia/pull/54002

2024-05-30 19:26 UTC, mkitti commented
This looks like a breaking change. Could we deprecate  the use of `ByteData` before we remove it?

2024-05-30 20:09 UTC, nhz2 commented
This is a bug fix. It isn't possible to turn a general CodeUnits into a Memory. Is there any not already buggy code this would break?

2024-05-31 07:08 UTC, jakobnissen commented
The constructor is unused in the codebase, unexported, and explicitly mentioned to be internal in the documentation. I would rather see that constructor completely removed.

2024-05-31 07:09 UTC, jakobnissen requested changes
IMO, remove this constructor completely, also from the docs. Make the user pass in a pointer themselves if they need this type.

2024-05-31 14:30 UTC, mkitti commented
I agree with the change. Possibly agree with removing the constructor. How is `Memory` usually constructed?

2024-05-31 14:51 UTC, nhz2 commented
To remove the `Memory(::Vector{UInt8})` constructor, https://github.com/JuliaIO/CodecLz4.jl/blob/55c2c423f8b757f2325dc83dd5473107375f823c/test/frame_compression.jl#L55-L56 would need to be updated. Though I agree that this should be removed, it already caused some issues, Ref: https://github.com/JuliaIO/CodecLz4.jl/pull/47

`Memory` is usually constructed with `Memory(ptr::Ptr{UInt8}, size::UInt)`

2024-06-01 04:11 UTC, mkitti commented
While I agree with @jakobnissen that there is a more fundamental issue, I think this pull request can go through to advance things in the right direction. I suspect that we will need a more fundamental refactoring here to eliminate free pointers hanging around.

2024-06-24 04:03 UTC, mkitti approved these changes

2024-06-24 16:40 UTC, merged